server.port=8080
spring.application.name=poseidon-ui

# On d\u00E9sactive le cache Thymeleaf pour voir les modifs HTML sans red\u00E9marrer
spring.thymeleaf.cache=false

# Lien vers le serveur de config (en option pour l'instant)
spring.config.import=optional:configserver:http://localhost:8071/

# Enregistrement dans Consul
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true

# Permet \u00E0 Consul de voir si le service est vivant
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Indique \u00E0 Spring de respecter les en-t\u00EAtes envoy\u00E9s par la Gateway
server.forward-headers-strategy=framework

spring.main.allow-bean-definition-overriding=true



# ===================================================================
# CONFIGURATION DES CIRCUIT BREAKERS (RESILIENCE4J)
# ===================================================================

# 1. Activation globale pour OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true

# 2. Configuration partag\u00E9e (par d\u00E9faut)
# Si 50% des appels \u00E9chouent sur une fen\u00EAtre de 5 appels, on ouvre le circuit
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.sliding-window-size=5

# 3. Application de la config \u00E0 chaque instance d\u00E9finie dans tes Controllers
resilience4j.circuitbreaker.instances.bidlistService.base-config=default
resilience4j.circuitbreaker.instances.curvepointService.base-config=default
resilience4j.circuitbreaker.instances.ratingService.base-config=default
resilience4j.circuitbreaker.instances.tradeService.base-config=default
resilience4j.circuitbreaker.instances.rulenameService.base-config=default

# 4. Dur\u00E9e d'attente avant de tenter de "refermer" le disjoncteur (10 secondes)
# Pendant ces 10 secondes, le message de maintenance restera affich\u00E9 quoi qu'il arrive.
resilience4j.circuitbreaker.instances.bidlistService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.curvepointService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ratingService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.tradeService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.rulenameService.wait-duration-in-open-state=10s

# Configuration pour le service User
resilience4j.circuitbreaker.instances.userService.base-config=default
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s


#Explication des r\u00E9glages
#failure-rate-threshold=50 : Si la moiti\u00E9 des demandes vers un microservice \u00E9chouent, le disjoncteur "saute".
#
#sliding-window-size=5 : Le disjoncteur prend sa d\u00E9cision en regardant les 5 derniers appels. C'est tr\u00E8s r\u00E9actif.
#
#wait-duration-in-open-state=10s : C'est le temps de repos. Si le service est en panne, l'UI attendra 10 secondes avant de retenter une connexion. Cela laisse le temps au microservice de red\u00E9marrer sans \u00EAtre "bombard\u00E9" de demandes.